### ISSUE TITLE
Bug Report: Tabela permite ordenação de múltiplas colunas

### ISSUE THREAD

**Issue by PedroLuisBrilhadori** [PedroLuisBrilhadori/my-pdv-front#2]
### Descrição do problema
Atualmente, a tabela na página de visualização apresenta um bug em que é possível ordenar mais de uma coluna ao mesmo tempo, o que não deveria ser permitido. Isso causa confusão para os usuários e pode levar a dados incorretamente ordenados.

### Como reproduzir
1. Abra a página de visualização da tabela.
2. Clique no cabeçalho de uma coluna para ordenar a tabela.
3. Clique em outro cabeçalho de coluna para ordenar por múltiplas colunas.
4. Observe que a tabela é ordenada por mais de uma coluna, o que não deveria ser possível.

### Comportamento esperado
Quando o usuário clica em um segundo cabeçalho de coluna, a tabela deveria ser ordenada apenas por essa coluna, e não por múltiplas colunas.

### Comportamento atual
A tabela é ordenada por múltiplas colunas quando um segundo cabeçalho de coluna é clicado.

### Screenshots
![image](https://user-images.githubusercontent.com/74775672/231276322-b951617b-2398-4190-bce6-f13baada196b.png)

### Ambiente de teste
- Sistema operacional: Ubuntu 20.10
- Navegador: Edge 112.0.1722.39

**Comment by Jbnado** [comment]
Esse bug já foi fechado né?
